import './base';
import './home';
import './insurance';
import './insurance/tabs';
import './insurance/banner';
import './insurance/payment-form';
import './insurance/calculator-form';
import './additional';
import './additional/game';
import './additional/writer-form';
import './additional/map';
import './additional/tabs';
import './uknown';

import './common/accountTable';
import './common/title';
import './home/account';
import './home/banners';
import './home/homeBanner';
