import './style.css';
import './theme/index';
import './settings';
import './components/ui/index';
import './data/index';
import './layout/index';
import './pages/index';
import './components/header/index';
import './components/footer/index';
